export const itemNames: string[] = [
  'A Dab of Ink',
  'A Mother\'s Parting Gift',
  'Abandoned Wealth',
  'Abberath\'s Horn',
  'Abyss Map',
  'Abyssus',
  'Academy Map',
  'Acid Caverns Map',
  'Acid Lakes Map',
  'Acton\'s Nightmare',
  'Advancing Fortress',
  'Agnerod East',
  'Agnerod North',
  'Agnerod South',
  'Agnerod West',
  'Ahkeli\'s Meadow',
  'Ahkeli\'s Mountain',
  'Ahkeli\'s Valley',
  'Ahn\'s Heritage',
  'Ahn\'s Might',
  'Akil\'s Prophecy',
  'Al Dhih',
  'Albino Rhoa Feather',
  'Alleyways Map',
  'Allure',
  'Alluring Bounty',
  'Alone in the Darkness',
  'Altered Distant Memory',
  'Amber Oil',
  'Amplification Rod',
  'Anarchy\'s Price',
  'Anatomical Knowledge',
  'Ancient City Map',
  'Ancient Orb',
  'Ancient Shard',
  'Ancient Waystones',
  'Andvarius',
  'Angler\'s Plait',
  'Annulment Shard',
  'Apep\'s Rage',
  'Apprentice Cartographer\'s Seal',
  'Arachnid Nest Map',
  'Arachnid Tomb Map',
  'Araku Tiki',
  'Arborix',
  'Arcade Map',
  'Arena Map',
  'Arid Lake Map',
  'Armourer\'s Scrap',
  'Armoury Map',
  'Arrogance of the Vaal',
  'Arsenal Map',
  'Ascent From Flesh',
  'Ashcaller',
  'Ashen Wood Map',
  'Asphyxia\'s Wrath',
  'Assassin\'s Haste',
  'Assassin\'s Favour',
  'Astral Projector',
  'Astramentis',
  'Atoll Map',
  'Atziri\'s Acuity',
  'Atziri\'s Foible',
  'Atziri\'s Promise',
  'Atziri\'s Reign',
  'Atziri\'s Arsenal',
  'Audacity',
  'Augmented Distant Memory',
  'Augyre',
  'Aul\'s UprisingAuxium',
  'Awakened Sextant',
  'Awakener\'s Orb',
  'Axiom Perpetuum',
  'Azure Oil',
  'Azyran\'s Reward',
  'Badge of the Brotherhood',
  'Baited Expectations',
  'Balefire',
  'Barrows Map',
  'Basilica Map',
  'Bated Breath',
  'Bazaar Map',
  'Beach Map',
  'Beacon Map',
  'Beauty Through Death',
  'Belfry Map',
  'Belt of the Deceiver',
  'Beltimber Blade',
  'Berek\'s Grip',
  'Berek\'s Pass',
  'Berek\'s Respite',
  'Bestiary Orb',
  'Binding Shard',
  'Birth of the Three',
  'Bisco\'s Collar',
  'Bisco\'s Leash',
  'Bitterdream',
  'Black Oil',
  'Blackgleam',
  'Blackheart',
  'Blacksmith\'s Whetstone',
  'Blessed Orb',
  'Blessing of God',
  'Blightwell',
  'Blind Venture',
  'Blood Sacrifice',
  'Blood of Corruption',
  'Blood of the Karui',
  'Bloodboil',
  'Bloodgrip',
  'Bloodplay',
  'Bloodseeker',
  'Bog Map',
  'Bone Crypt Map',
  'Boon of Justice',
  'Boon of the First Ones',
  'Bottled Faith',
  'Boundless Realms',
  'Bowyer\'s Dream',
  'Bramblejack',
  'Brawn',
  'Breath of the Council',
  'Brightbeak',
  'Brinerot Mark',
  'Brittle Barrier',
  'Brutal Restraint',
  'Brute Force Solution',
  'Brutus\' Lead Sprinkler',
  'Burial Chambers Map',
  'Buried Treasure',
  'Burning Blood',
  'Caer Blaidd, Wolfpack\'s Den',
  'Cage Map',
  'Caldera Map',
  'Call of the Brotherhood',
  'Call to the First Ones',
  'Callinellus Malleus',
  'Cameria\'s Avarice',
  'Cameria\'s Maul',
  'Cameria\'s Cut',
  'Canyon Map',
  'Carcass Map',
  'Careful Planning',
  'Carnage Heart',
  'Cartographer\'s Chisel',
  'Cartographer\'s Delight',
  'Castle Ruins Map',
  'Catacombs Map',
  'Cavern Map',
  'Cells Map',
  'Cemetery Map',
  'Cerberus Limb',
  'Channel Map',
  'Chaos Orb',
  'Chaos Shard',
  'Chaotic Disposition',
  'Chateau Map',
  'Chayula\'s Breachstone',
  'Cheap Construction',
  'Chernobog\'s Pillar',
  'Chill of Corruption',
  'Chin Sol',
  'Choir of the Storm',
  'Chromatic Orb',
  'Cinderswallow Urn',
  'Circle of Anguish',
  'Circle of Fear',
  'Circle of Guilt',
  'Circle of Nostalgia',
  'Circle of Regret',
  'City Square Map',
  'Clayshaper',
  'Clear Mind',
  'Clear Oil',
  'Coated Shrapnel',
  'Cold Steel',
  'Colonnade Map',
  'Colosseum Map',
  'Combat Focus',
  'Combustibles',
  'Conqueror\'s Efficiency',
  'Conqueror\'s Longevity',
  'Conqueror\'s Potency',
  'Conservatory Map',
  'Coral Ruins Map',
  'Core Map',
  'Corona Solaris',
  'Corrupted Energy',
  'Cortex',
  'Coruscating Elixir',
  'Courthouse Map',
  'Courtyard Map',
  'Coves Map',
  'Coveted Possession',
  'Coward\'s Chains',
  'Coward\'s Legacy',
  'Cowl of the Thermophile',
  'Cragfall',
  'Craghead',
  'Craiceann\'s Carapace',
  'Craiceann\'s Pincers',
  'Craiceann\'s Tracks',
  'Crater Map',
  'Crematorium Map',
  'Crimson Oil',
  'Crimson Temple Map',
  'Crusader\'s Exalted Orb',
  'Crypt Map',
  'Crystal Ore Map',
  'Cursed Crypt Map',
  'Cybil\'s Paw',
  'Cyclopean Coil',
  'Daresso\'s Salute',
  'Dark Dreams',
  'Dark Forest Map',
  'Dark Temptation',
  'Darkness Enthroned',
  'Darkscorn',
  'Dead Reckoning',
  'Death',
  'Death Rush',
  'Death and TaxesDeath\'s Hand',
  'Death\'s Harp',
  'Death\'s Oath',
  'Death\'s Opus',
  'Deathly Designs',
  'Defiled Cathedral Map',
  'Demigod\'s Wager',
  'Desert Map',
  'Desert Spring Map',
  'Destined to Crumble',
  'Dialla\'s Subjugation',
  'Dig Map',
  'Divide and Conquer',
  'Divination Distillate',
  'Divine Justice',
  'Divine Orb',
  'Divine Vessel',
  'Doedre\'s Damning',
  'Doedre\'s Elixir',
  'Doedre\'s Madness',
  'Doomfletch',
  'Doomfletch\'s Prism',
  'Doon Cuebiyari',
  'Doryani\'s Catalyst',
  'Doryani\'s Delusion',
  'Doryani\'s Fist',
  'Doryani\'s Invitation',
  'Doryani\'s Machinarium',
  'Dreadarc',
  'Dreadbeak',
  'Dreadsurge',
  'Dream Fragments',
  'Dreamfeather',
  'Drillneck',
  'Dunes Map',
  'Dungeon Map',
  'Dyadian Dawn',
  'Dyadus',
  'Dying Anguish',
  'Dying Sun',
  'Earendel\'s Embrace',
  'Earth Drinker',
  'Eber\'s Key',
  'Echoes of Love',
  'Eclipse Solaris',
  'Efficient Training',
  'Eldritch Knowledge',
  'Elegant Hubris',
  'Emberwake',
  'Emperor of Purity',
  'Emperor\'s Cunning',
  'Emperor\'s Mastery',
  'Emperor\'s Might',
  'Emperor\'s Wit',
  'Emperor\'s Luck',
  'Empire\'s Grasp',
  'Energised Armour',
  'Energy From Within',
  'Engineer\'s Orb',
  'Engineer\'s Shard',
  'Ephemeral Edge',
  'Esh\'s Breachstone',
  'Essence Worm',
  'Essence of Anger',
  'Essence of Anguish',
  'Essence of Contempt',
  'Essence of Delirium',
  'Essence of Doubt',
  'Essence of Dread',
  'Essence of Envy',
  'Essence of Fear',
  'Essence of Greed',
  'Essence of Hatred',
  'Essence of Horror',
  'Essence of Hysteria',
  'Essence of Insanity',
  'Essence of Loathing',
  'Essence of Misery',
  'Essence of Rage',
  'Essence of Scorn',
  'Essence of Sorrow',
  'Essence of Spite',
  'Essence of Suffering',
  'Essence of Torment',
  'Essence of Woe',
  'Essence of Wrath',
  'Essence of Zeal',
  'Essentia Sanguis',
  'Estuary Map',
  'Etched in Blood',
  'Eternal Orb',
  'Exalted Orb',
  'Exalted Shard',
  'Excavation Map',
  'Extractor Mentis',
  'Eye of Chayula',
  'Eye of Innocence',
  'Eyes of the Greatwolf',
  'Ezomyte Hold',
  'Ezomyte Peak',
  'Factory Map',
  'Faminebind',
  'Fate of the Vaal',
  'Feastbind',
  'Femurs of the Saints',
  'Fencoil',
  'Fertile Mind',
  'Fevered Mind',
  'Fields Map',
  'Fight for Survival',
  'Fireborn',
  'First Snow',
  'Flesh-Eater',
  'Flooded Mine Map',
  'Fluid Motion',
  'Forbidden Power',
  'Forbidden Taste',
  'Forge of the Phoenix Map',
  'Fortress Covenant',
  'Fragile Bloom',
  'Fragility',
  'Fragment of Constriction',
  'Fragment of Emptiness',
  'Fragment of Enslavement',
  'Fragment of Eradication',
  'Fragment of Knowledge',
  'Fragment of Purification',
  'Fragment of Shape',
  'Fragment of Terror',
  'Fragment of the Chimera',
  'Fragment of the Hydra',
  'Fragment of the Minotaur',
  'Fragment of the Phoenix',
  'Friendship',
  'From Dust',
  'Frostbreath',
  'Frozen Trail',
  'Fungal Hollow Map',
  'Fury Valve',
  'Gardens Map',
  'Gemcutter\'s Prism',
  'Gemcutter\'s Promise',
  'Geode Map',
  'Ghetto Map',
  'Giantsbane',
  'Gift of the Gemling Queen',
  'Gifts from Above',
  'Glacier Map',
  'Glassblower\'s Bauble',
  'Glimmer of Hope',
  'Gloomfang',
  'Glorious Vanity',
  'Gluttony',
  'Golden Oil',
  'Gorebreaker',
  'Goredrill',
  'Gorge Map',
  'Grand Spectrum',
  'Grave Knowledge',
  'Graveyard Map',
  'Greed\'s Embrace',
  'Grelwood Shank',
  'Grotto Map',
  'Growing Agony',
  'Hair Trigger',
  'Hall of Grandmasters',
  'Hallowed Ground',
  'Hand of Thought and Motion',
  'Hand of Wisdom and Action',
  'Harbinger Map',
  'Harbinger\'s Orb',
  'Harbinger\'s Shard',
  'Harmony of Souls',
  'Haunted Mansion Map',
  'Hazardous Research',
  'Headhunter',
  'Healthy Mind',
  'Heartbound Loop',
  'Her Mask',
  'Heterochromia',
  'Hidden Potential',
  'High Gardens Map',
  'Hinekora\'s Sight',
  'Hope',
  'Hopeshredder',
  'Horizon Shard',
  'Hotfooted',
  'House of Mirrors',
  'Hrimnor\'s Resolve',
  'Hubris',
  'Humility',
  'Hungry Abyss',
  'Hunter\'s Exalted Orb',
  'Hunter\'s Resolve',
  'Hunter\'s Reward',
  'Hyaon\'s Fury',
  'Hyperboreus',
  'Hyrri\'s Bite',
  'Hyrri\'s Demise',
  'Hyrri\'s Truth',
  'Iceberg Map',
  'Icefang Orbit',
  'Ichimonji',
  'Immortal Flesh',
  'Immortal Resolve',
  'Imperial Legacy',
  'Impresence',
  'Imprinted Bestiary Orb',
  'Inertia',
  'Inevitability',
  'Infested Valley Map',
  'Infractem',
  'Innsbury Edge',
  'Inspired Learning',
  'Intuitive Leap',
  'Inya\'s Key',
  'Iron Commander',
  'Iron Heart',
  'Ivory Temple Map',
  'Ivory Watchstone',
  'Izaro\'s Dilemma',
  'Izaro\'s Turmoil',
  'Jack in the Box',
  'Jack, the Axe',
  'Jeweller\'s Orb',
  'Journeyman Cartographer\'s Seal',
  'Jungle Valley Map',
  'Kaom\'s Heart',
  'Kaom\'s Roots',
  'Kaom\'s Sign',
  'Kaom\'s Way',
  'Karui Charge',
  'Karui Ward',
  'Kiara\'s Determination',
  'Kikazaru',
  'Laboratory Map',
  'Lair Map',
  'Lair of the Hydra Map',
  'Lakishu\'s Blade',
  'Lantador\'s Lost Love',
  'Last Hope',
  'Last Resort',
  'Lava Chamber Map',
  'Lava Chambers Map',
  'Lava Lake Map',
  'Lavianga\'s Spirit',
  'Lavianga\'s Wisdom',
  'Le Heup of All',
  'Leash of Oblation',
  'Left to Fate',
  'Lethal Pride',
  'Leyline Map',
  'Lifesprig',
  'Light and Truth',
  'Lighthouse Map',
  'Lingering Remnants',
  'Lion\'s Roar',
  'Lioneye\'s Fall',
  'Lioneye\'s Glare',
  'Lioneye\'s Remorse',
  'Lioneye\'s Vision',
  'Lochtonial Caress',
  'Lookout Map',
  'Lori\'s Lantern',
  'Lost Worlds',
  'Loyalty',
  'Lucky Connections',
  'Lucky Deck',
  'Lycosidae',
  'Lysah\'s Respite',
  'Maelström of Chaos',
  'Magna Eclipsis',
  'Malachai\'s Artifice',
  'Malformation Map',
  'Malicious Intent',
  'Maligaro\'s Cruelty',
  'Maligaro\'s Restraint',
  'Maloney\'s Mechanism',
  'Maloney\'s Nightfall',
  'Mantra of Flames',
  'Mao KunMark of Submission',
  'Mark of the Elder',
  'Mark of the Shaper',
  'Marshes Map',
  'Martial Artistry',
  'Martyr of Innocence',
  'Marylene\'s Fallacy',
  'Master Cartographer\'s Seal',
  'Mausoleum Map',
  'Mawr Blaidd',
  'Maze Map',
  'Maze of the Minotaur Map',
  'Meginord\'s Girdle',
  'Meginord\'s Vise',
  'Merciless Armament',
  'Mesa Map',
  'Midnight Bargain',
  'Might and Influence',
  'Might in All Forms',
  'Might is Right',
  'Might of the Meek',
  'Mightflay',
  'Militant Faith',
  'Mineral Pools Map',
  'Ming\'s Heart',
  'Mirebough',
  'Mirror Shard',
  'Mirror of Kalandra',
  'Mitts',
  'Mjölner',
  'Mokou\'s Embrace',
  'Mon\'tregul\'s Grasp',
  'Monochrome',
  'Moon Temple Map',
  'Moonbender\'s Wing',
  'Moonsorrow',
  'More is Never Enough',
  'Mortal Grief',
  'Mortal Hope',
  'Mortal Ignorance',
  'Mortal Rage',
  'Mortem Morsu',
  'Mother\'s Embrace',
  'Mud Geyser Map',
  'Museum Map',
  'Mutated Growth',
  'Mutewind Seal',
  'Natural Hierarchy',
  'NebulisNebuloch',
  'Necropolis Map',
  'Ngamahu Tiki',
  'Ngamahu\'s Sign',
  'Night\'s Hold',
  'No Traces',
  'Nook\'s Crown',
  'Null\'s Inclination',
  'Nuro\'s Harp',
  'Nycta\'s Lantern',
  'Oasis Map',
  'Oba\'s Cursed Trove',
  'Obliteration',
  'Offering to the Goddess',
  'Olmec\'s Sanctum',
  'Omen on the Winds',
  'Oni-Goroshi',
  'Opalescent Oil',
  'Orb of Alchemy',
  'Orb of Alteration',
  'Orb of Annulment',
  'Orb of Augmentation',
  'Orb of Binding',
  'Orb of Chance',
  'Orb of Fusing',
  'Orb of Horizons',
  'Orb of Regret',
  'Orb of Scouring',
  'Orb of Transmutation',
  'Ornament of the East',
  'Overwhelming Odds',
  'Pacifism',
  'Perandus Blazon',
  'Perandus Coin',
  'Perandus Signet',
  'Perfection',
  'Perquil\'s Toe',
  'Perseverance',
  'Pillars of Arun',
  'Piscator\'s Vigil',
  'Poacher\'s Aim',
  'Poorjoy\'s Asylum',
  'Portal Scroll',
  'Powerlessness',
  'Praxis',
  'Precursor\'s Emblem',
  'Presence of Chayula',
  'Pride Before the Fall',
  'Pride of the First Ones',
  'Prime Sextant',
  'Primordial Eminence',
  'Primordial Harmony',
  'Primordial Might',
  'Prismatic Eclipse',
  'Prismweave',
  'Prosperity',
  'Pugilist',
  'Pure Talent',
  'Putembo\'s Meadow',
  'Putembo\'s Mountain',
  'Putembo\'s Valley',
  'Pyre',
  'Quickening Covenant',
  'Quill Rain',
  'Rain Tempter',
  'Rain of Chaos',
  'Rain of Splinters',
  'Rapid Expansion',
  'Rashkaldor\'s Patience',
  'Rats',
  'Razor of the Seventh Sun',
  'Reach of the Council',
  'Rearguard',
  'Rebirth',
  'Rebuke of the Vaal',
  'Reckless Defence',
  'Redbeak',
  'Redblade Band',
  'Redblade Banner',
  'Redblade Tramplers',
  'Redeemer\'s Exalted Orb',
  'Reefbane',
  'Regal Orb',
  'Regal Shard',
  'Relentless Fury',
  'Remembrance',
  'Remnant of Corruption',
  'Reverberation Rod',
  'Rewritten Distant Memory',
  'Rigwald\'s Command',
  'Rigwald\'s Crest',
  'Rigwald\'s Curse',
  'Rigwald\'s Quills',
  'Rigwald\'s Savagery',
  'Ring of Blades',
  'Rive',
  'Rolling Flames',
  'Romira\'s Banquet',
  'Rotgut',
  'Roth\'s Reach',
  'Rumi\'s Concoction',
  'Ryslatha\'s Coil',
  'Sacrifice at Dawn',
  'Sacrifice at Dusk',
  'Sacrifice at Midnight',
  'Sacrifice at Noon',
  'Sacrificial Harvest',
  'Sacrificial Heart',
  'Saemus\' Gift',
  'Sambodhi\'s Vow',
  'Sanguine Gambol',
  'Scaeva',
  'Scholar of the Seas',
  'Scroll of Wisdom',
  'Self-Flagellation',
  'Sepia Oil',
  'Seven Years Bad Luck',
  'Severed in Sleep',
  'Shade of Solaris',
  'Shaper\'s Seed',
  'Shard of Fate',
  'Shattered Chains',
  'Shavronne\'s Revelation',
  'Shimmeron',
  'Sibyl\'s Lament',
  'Sidhebreath',
  'Siegebreaker',
  'Sign of the Sin Eater',
  'Silver Coin',
  'Silver Oil',
  'Silverbough',
  'Silverbranch',
  'Simple Sextant',
  'Sin\'s Rebirth',
  'Singularity',
  'Skirmish',
  'Slivertongue',
  'Snakepit',
  'Solaris Lorica',
  'Solstice Vigil',
  'Song of the Sirens',
  'Soul Catcher',
  'Soul Ripper',
  'Soul Strike',
  'Soul Taker',
  'Soul Tether',
  'Soul\'s Wick',
  'Soulthirst',
  'Spine of the First Claimant',
  'Spire of Stone',
  'Spirit Guards',
  'Spirited Response',
  'Splinter of Chayula',
  'Splinter of Esh',
  'Splinter of Tul',
  'Splinter of Uul-Netol',
  'Splinter of Xoph',
  'Spreading Rot',
  'Squandered Prosperity',
  'Stacked Deck',
  'Star of Wraeclast',
  'Static Electricity',
  'Steel Spirit',
  'Stone of Lazhwar',
  'Storm Cloud',
  'Storm Prison',
  'Stormcharger',
  'Stormfire',
  'Story of the Vaal',
  'String of Servitude',
  'Struck by Lightning',
  'Succor of the Sinless',
  'Sunblast',
  'Survival Instincts',
  'Survival Secrets',
  'Survival Skills',
  'Taproot',
  'Tasalio\'s Sign',
  'Taste of Hate',
  'Tavukai',
  'Teal Oil',
  'Tear of Purity',
  'Tempered Flesh',
  'Tempered Mind',
  'Tempered Spirit',
  'The Admirer',
  'The Aesthete',
  'The Anima Stone',
  'The Anticipation',
  'The Anvil',
  'The Archmage\'s Right Hand',
  'The Arena Champion',
  'The Ascetic',
  'The Aylardex',
  'The Baron',
  'The Beachhead',
  'The Black Cane',
  'The Blood Thorn',
  'The Blue Dream',
  'The Blue Nightmare',
  'The Brass Dome',
  'The Coward\'s Trial',
  'The Crimson Storm',
  'The Dark SeerThe Effigon',
  'The Enmity Divine',
  'The Flow Untethered',
  'The Formless Flame',
  'The Formless Inferno',
  'The Fracturing Spinner',
  'The Goddess Scorned',
  'The Golden Rule',
  'The Green Dream',
  'The Green Nightmare',
  'The Gryphon',
  'The Halcyon',
  'The Hungry Loop',
  'The Ignomon',
  'The Infinite Pursuit',
  'The Iron Fortress',
  'The Jinxed Juju',
  'The Long Winter',
  'The Magnate',
  'The Nomad',
  'The Overflowing Chalice',
  'The Pandemonius',
  'The Pariah',
  'The Perandus Manor',
  'The Poet\'s Pen',
  'The Primordial Chain',
  'The Princess',
  'The Putrid Cloister',
  'The Red Dream',
  'The Red Nightmare',
  'The Red Trail',
  'The Retch',
  'The Rippling Thoughts',
  'The Saviour',
  'The Scourge',
  'The Screaming Eagle',
  'The Searing Touch',
  'The Signal Fire',
  'The Sorrow of the Divine',
  'The Stormheart',
  'The Stormwall',
  'The Supreme Truth',
  'The Surrender',
  'The Tactician',
  'The Taming',
  'The Tempest',
  'The Tempestuous Steel',
  'The Twilight Temple',
  'The Vigil',
  'The Vinktar Square',
  'The Warden\'s Brand',
  'The Wasp Nest',
  'The Wise Oak',
  'The Writhing Jar',
  'Thief\'s Torment',
  'Thread of Hope',
  'Timeclasp',
  'Timeless Eternal Empire Splinter',
  'Timeless Karui Splinter',
  'Timeless Maraketh Splinter',
  'Timeless Templar Splinter',
  'Timeless Vaal Splinter',
  'Timetwist',
  'Titucius\' Span',
  'To Dust',
  'Torchoak Step',
  'Touch of Anguish',
  'Transcendent Flesh',
  'Transcendent Mind',
  'Transcendent Spirit',
  'Trolltimber Spire',
  'Tukohama\'s Fortress',
  'Tul\'s Breachstone',
  'Tulborn',
  'Tulfall',
  'Twisted Distant Memory',
  'Twyzel',
  'Umbilicus Immortalis',
  'Unending Hunger',
  'Ungil\'s Harmony',
  'United in Dream',
  'Unnatural Instinct',
  'Unshaping Orb',
  'Unstable Payload',
  'Uul-Netol\'s Breachstone',
  'Uzaza\'s Meadow',
  'Uzaza\'s Mountain',
  'Uzaza\'s Valley',
  'Vaal Orb',
  'Vaal Sentencing',
  'Valako\'s Sign',
  'Valyrium',
  'Varunastra',
  'Vaults of Atziri',
  'Venopuncture',
  'Ventor\'s Gamble',
  'Verdant Oil',
  'Veruso\'s Battering Rams',
  'Vessel of Vinktar',
  'Vial of Awakening',
  'Vial of Consequence',
  'Vial of Dominance',
  'Vial of Fate',
  'Vial of Sacrifice',
  'Vial of Summoning',
  'Vial of Transcendence',
  'Vial of the Ghost',
  'Vial of the Ritual',
  'Victario\'s Acuity',
  'Violet Oil',
  'Vivinsect',
  'Voice of the Storm',
  'Void Battery',
  'Voideye',
  'Voidfletcher',
  'Voidheart',
  'Volkuur\'s Key',
  'Voll\'s Devotion',
  'Volley Fire',
  'Voltaxic Rift',
  'Wall of Brambles',
  'Warlord\'s Reach',
  'Warlord\'s Exalted Orb',
  'Warped Timepiece',
  'Warrior\'s Legacy',
  'Watcher\'s Eye',
  'Weight of Sin',
  'Weight of the Empire',
  'Whakawairua Tuahu',
  'Wildfire',
  'Wildslash',
  'Willowgift',
  'Windripper',
  'Winds of Change',
  'Windscream',
  'Windshriek',
  'Winter Burial',
  'Winter\'s Bounty',
  'Winterheart',
  'Winterweave',
  'Witchfire Brew',
  'Wurm\'s Molt',
  'Xoph\'s Blood',
  'Xoph\'s Heart',
  'Xoph\'s Inception',
  'Xoph\'s Nurture',
  'Xoph\'s Breachstone',
  'Yoke of Suffering',
  'Yriel\'s Key',
  'Zerphi\'s Heart',
  'Zerphi\'s Last Breath',
];
