export const enum ClassTypes {
  SCION = 'Scion',
  ASCENDANT = 'Ascendant',
  MARAUDER = 'Marauder',
  BERSERKER = 'Berserker',
  JUGGERNAUT = 'Juggernaut',
  CHIEFTAIN = 'Chieftain',
  RANGER = 'Ranger',
  DEADEYE = 'Deadeye',
  RAIDER = 'Raider',
  PATHFINDER = 'Pathfinder',
  WITCH = 'Witch',
  NECROMANCER = 'Necromancer',
  OCCULTIST = 'Occultist',
  ELEMENTALIST = 'Elementalist',
  DUELIST = 'Duelist',
  SLAYER = 'Slayer',
  GLADIATOR = 'Gladiator',
  CHAMPION = 'Champion',
  TEMPLAR = 'Templar',
  INQUISITOR = 'Inquisitor',
  HIEROPHANT = 'Heirophant',
  GUARDIAN = 'Guardian',
  SHADOW = 'Shadow',
  ASSASSIN = 'Assassin',
  SABOTEUR = 'Saboteur',
  TRICKSTER = 'Trickster',
}
